// src/routes/signup/+page.svelte
<script lang="ts">
// Imports
import { goto } from '$app/navigation';

// Server values
export let form:{
	status:String,
	message:String
};

// Code starts here
let message:String;
let username:String = "";
let password:String = "";
let confirm:String = "";
let loading:Boolean = false;

const submitForm = async () => {
	if (password !== confirm) {
		message = "Passwords do not match";
		return;
	}

	loading = true;
	const reqBody = {
		"username": username,
		"password": password
	}

	const response = await fetch("/api/signup", {
		method: "POST",
		headers: {
			"Content-Type": "application/json"
		},
		body: JSON.stringify(reqBody)
	});

	const data = await response.json();
	console.log(data)
	if (data.status === "Success") {
		alert(`Signed up as ${username}`)
		goto("/login");
	} else {
		message = data.message;
	}
	loading = false;
}

</script>

<svelte:head>
	<title>Sign Up</title>
</svelte:head>

<main>
	<h1>Sign up</h1>
	<form on:submit|preventDefault={submitForm} >
		{#if message}
			<span class="error">{message}</span>
		{/if}
		<input bind:value={username} type="text" name="username" placeholder="Username" required>
		<input bind:value={password} type="password" name="password" placeholder="Password" required>
		<input bind:value={confirm} type="password" name="confirm" placeholder="Confirm Password" required>
		<input type="submit" value="Sign Up">
		<div>
			Already have an account? <a href="/login">Login</a>
		</div>
	</form>

	{#if loading}
		<div class="loading">
			<div class="circle_thingy"></div>
		</div>
	{/if}
</main>

<style>

main {
	grid-row: 2/12;
	grid-column: 1/13;

	display: flex;
	flex-direction: column;
	justify-content: center;
	align-items: center;
	gap: 1rem;

	position: relative;
}

.loading {
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
	z-index: 5;
	background-color: rgba(0,0,0,0.5);

	display: flex;
	justify-content: center;
	align-items: center;
}

@keyframes spin {
	0% {
		transform: rotate(0deg);
	}
	100% {
		transform: rotate(360deg);
	}
}

.circle_thingy {
	width: 100px;
	height: 100px;
	border: 5px solid var(--secondary);
	border-top-color: transparent;
	border-bottom-color: transparent;
	animation: spin 1s linear infinite;
	border-radius: 100%;
}

form {
	display: flex;
	flex-direction: column;
	gap: 1rem;
}

input[type="submit"] {
	background-color: var(--buttons);
	color: var(--text);
	padding: 0.5rem;
	border: none;
	cursor: pointer;
}

input {
	padding: 0.5rem;
	border: 1px solid var(--secondary);
}

a {
	color: var(--buttons);
}

.error {
	width: 100%;
	text-align: center;
	color: var(--buttons);
}

</style>

// src/app/signup/page.tsx
'use client'

import { useRouter } from "next/navigation";
import {useState} from "react"

export default function Signup() {
	const router = useRouter();
	const [uname, setUname] = useState("");
	const [password, setPassword] = useState("");
	const [confirm, setConfirm] = useState("");

	const handleSubmit = async (e:any) => {
		e?.preventDefault();

		if (password !== confirm) {
			alert("Passwords do not match");
			return;
		}

		const data = {
			uname: uname,
			pass: password
		}

		const res = await fetch("/api/signup", {
			method: "POST",
			body: JSON.stringify(data)
		})

		const json = await res.json();
		if (json.status == 'success') {
			alert("Signed up successfully");
			router.push("/login")
		} else if (json.status == 'error') {
			if (json.message == 'User already exists') {
				alert("User already exists");
				router.push("/login")
			} else {
				alert(json.message);
			}
		} else {
			alert("An error occurred")
		}
	}

	return (
		<main className="w-dvw h-dvh flex justify-center items-center">
			<form onSubmit={handleSubmit} className="flex flex-col justify-center items-center gap-6 p-6 bg-neutral-800">
				<input value={uname} onChange={(e) => setUname(e.target.value)} name="uname" className="p-4 bg-transparent border border-white" type="text" placeholder="Username"></input>
				<input value={password} onChange={(e) => setPassword(e.target.value)} name="password" className="p-4 bg-transparent border border-white" type="password" placeholder="Password"></input>
				<input value={confirm} onChange={(e) => setConfirm(e.target.value)} name="confirm" className="p-4 bg-transparent border border-white" type="password" placeholder="Confirm password"></input>
				<input className="px-4 py-2 bg-white text-black border-none" type="submit" value="Signup"></input>
			</form>
		</main>
	)
}
